version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://server:5103
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5103:5103"
